name: GeoSite
on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run And Move
        run: |
          git clone https://github.com/Slotheve/xGeoSite.git
          chmod -R 777 xGeoSite && cd xGeoSite
          wget -O sites/cn https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
          wget -O site/icloud https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/icloud.txt
          wget -O site/apple https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt
          sed -i '/^.*microsoft.*/d' sites/cn && sed -i '/^.*speedtest.com*.*/d' sites/cn
          sed -i '/^.*apple*.*/d' sites/cn && sed -i '/^.*icloud*.*/d' sites/cn
          sed -i '/^.*mzstatic*.*/d' sites/cn && sed -i '/^.*xdmb*.*/d' sites/cn
          sed -i '/^.*akadns*.*/d' sites/cn && sed -i '/^.*edgekey*.*/d' sites/cn
          sed -i '/^.*aaplimg*.*/d' sites/cn && sed -i '/^.*google*.*/d' sites/cn
          sed -i '/^.*akamaihd*.*/d' sites/cn && sed -i '/^.*akamaized*.*/d' sites/cn
          touch sites/reject
          sed -i '1i\DOMAIN-KEYWORD,logsvr.ppio.cloud' sites/reject
          sed -i '1i\DOMAIN-KEYWORD,.va.huya.com' sites/reject
          sed -i '1i\DOMAIN-KEYWORD,szbdyd.com' sites/reject
          sed -i '1i\DOMAIN-KEYWORD,hw-sh-pcdn-' sites/reject
          sed -i '1i\DOMAIN-KEYWORD,p2p.huya.com' sites/reject
          sed -i '1i\DOMAIN-KEYWORD,statwup.huya.com' sites/reject
          ./v2sitedat
          mkdir -pv publish/clash publish/other publish/surge
          echo sites/apple sites/direct sites/down sites/proxy sites/micro | xargs -n 1 sed -i 's/^/DOMAIN-KEYWORD,/'
          sed -i '/^full\:/,$d' sites/cn && sed -i '$a\.cn' sites/cn && sed -i 's/^/DOMAIN-SUFFIX,/' sites/cn
          sha256sum geosite.dat > geosite.dat.sha256sum && cp {geosite.dat,geosite.dat.sha256sum} publish
          echo publish/other publish/surge | xargs -n 1 cp -v sites/*
          sed -i 's/^/  - /' sites/* && sed -i '1i\payload:' sites/* && cp sites/* publish/clash
          sed -i '$a\USER-AGENT,*TencentMidasConnect*' publish/surge/direct
          sed -i '$a\USER-AGENT,*WeChat*' publish/surge/direct
          sed -i '$a\USER-AGENT,*MicroMessenger*' publish/surge/direct
          sed -i '$a\USER-AGENT,*QQ*' publish/surge/direct

      - name: Generate Release
        id: tag
        run: |
          echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_date }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
          files: |
            ./xGeoSite/publish/*

      - name: Git push  to "Release"
        run: |
          cd xGeoSite/publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ steps.tag.outputs.release_date }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
