name: GeoSite
on:
  workflow_dispatch:
  #schedule:
    #- cron: "30 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #- name: Setup Go 1.x.y
        #uses: actions/setup-go@v3
        #with:
          #go-version: ^1.18

      - name: Run & Move
        run: |
          git clone https://github.com/Slotheve/GeoSite.git
          chmod -R 777 GeoSite
          cd GeoSite
          wget -O sites/cn https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt
          wget -O sites/reject https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt
          sed -i '/^.*microsoft.*/d' sites/cn
          sed -i '/^.*speedtest*.*/d' sites/cn
          sed -i '/^.*apple*.*/d' sites/cn
          sed -i '/^.*icloud*.*/d' sites/cn
          sed -i '/^.*mzstatic*.*/d' sites/cn
          sed -i '/^.*xdmb*.*/d' sites/cn
          sed -i '/^.*akadns*.*/d' sites/cn
          sed -i '/^.*edgekey*.*/d' sites/cn
          sed -i '/^.*aaplimg*.*/d' sites/cn
          sed -i '/^.*google*.*/d' sites/cn
          ./v2sitedat
          rm sites/game
          mkdir -pv publish/clash && mkdir -pv publish/other
          sed -i 's/^/DOMAIN-SUFFIX,/' sites/*
          sed -i '/^DOMAIN-SUFFIX\,full\:/,$d' sites/cn
          sed -i '/^DOMAIN-SUFFIX\,regexp\:/,$d' sites/cn
          sed -i '/^DOMAIN-SUFFIX\,regexp\:/,$d' sites/down
          sed -i '/^DOMAIN-SUFFIX\,regexp\:/,$d' sites/apple
          sed -i '$aDOMAIN-SUFFIX,bixi.alicdn.com' sites/reject
          sed -i 's/^DOMAIN-SUFFIX\,1drv/DOMAIN-KEYWORD,1drv/' sites/micro
          sed -i 's/^DOMAIN-SUFFIX\,msn/DOMAIN-KEYWORD,msn/' sites/micro
          sed -i 's/^DOMAIN-SUFFIX\,microsoft/DOMAIN-KEYWORD,microsoft/' sites/micro
          sha256sum geosite.dat > geosite.dat.sha256sum
          cp {geosite.dat,geosite.dat.sha256sum} publish && cp sites/* publish/other
          sed -i 's/^/  - /' sites/*
          sed -i '1i\payload:' sites/*
          wget -O sites/cnip https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt
          sed -i '1d' sites/cnip
          sed -i 's/^/ip-cidr,/' sites/cnip
          sed -i 's/$/,no-resolve/' sites/cnip
          cp sites/cnip publish/other
          cp sites/* publish/clash

      - name: Generate Release
        id: tag
        run: |
          echo "release_tag=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_date }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          draft: false
          prerelease: false
          files: |
            ./GeoSite/publish/*

      - name: Git push  to "Release"
        run: |
          cd GeoSite/publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ steps.tag.outputs.release_date }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
